---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: jwt-gateway
  labels:
    app.kubernetes.io/name: multi-tenant-saas-service
spec:
  selector:
    app: multi-tenant-saas-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
